### PR TITLE
update studio, dependencies, and some code

### PR DESCRIPTION
**Pull request by TacoTheDank**
- java 1.8 compatibility (replace anonymous java expressions with lambdas, etc)
- target pie
- android studio 3.2.1
- rearrange xml code

### CODE REVIEW

**Comment by dh4** [comment]
Thanks for this! I'm currently on vacation. I'll review the pull request and merge when I'm back.

**Comment by TacoTheDank** [comment]
nice, where are you vacationing?

**Comment by dh4** [comment]
Got around to merging this. Sorry for the delay. Thanks for the code improvements/contributions!

**Comment by TacoTheDank** [comment]
:P

**Pull request merged**
